[package]
name = "agent-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
"agent-lib" = { path = "../agent-lib" }
"agent-behavior" = { path = "../agent-behavior" }
"agent-world" = { path = "../agent-world" }